// Default service detail data — shared between frontend and admin.
// This is the hardcoded seed data. Admin edits override this via localStorage.

export interface ServiceDetailPageData {
  title: string;
  category: string;
  description: string;
  overview: string[];
  process: { step: number; title: string; description: string }[];
  deliverables: string[];
  pricing: { name: string; price: string; description: string; features: { text: string; included: boolean }[]; highlighted?: boolean }[];
  faqs: { question: string; answer: string }[];
  relatedSlugs: string[];
}

export const serviceDetailDefaults: Record<string, ServiceDetailPageData> = {
  'tracking-analytics': {
    title: 'Tracking & Analytics',
    category: 'Data & Measurement',
    description:
      'Implement precise, privacy-compliant tracking with GA4, Google Tag Manager, and server-side solutions so every marketing dollar is measurable and every conversion is attributed correctly.',
    overview: [
      'Accurate tracking is the foundation of every profitable marketing operation. Without reliable data, you are making decisions in the dark — overspending on channels that underperform and under-investing in the ones that actually drive revenue. I specialize in deploying end-to-end measurement systems built on Google Analytics 4, Google Tag Manager, and server-side tracking architectures that survive ad blockers, iOS restrictions, and evolving browser privacy policies. Whether you are running e-commerce, SaaS, or lead-generation campaigns, I configure data layers, enhanced conversions, and custom event schemas that capture the full customer journey from first click to closed deal.',
      'My approach goes beyond basic pageview tracking. I design attribution models that account for multi-touch interactions across paid search, organic, social, and email channels — giving you a clear picture of which touchpoints actually influence conversions. I also set up real-time dashboards in Looker Studio or BigQuery so your team can monitor KPIs without waiting for weekly reports. Server-side tagging through Google Tag Manager server containers ensures your data remains accurate even as third-party cookies disappear, future-proofing your measurement stack for the cookieless era.',
      'Every implementation follows a structured quality-assurance process: I validate data against source-of-truth systems, run parallel tracking tests, and document every tag, trigger, and variable so your team can maintain the setup long after the project ends. The result is a single source of truth your marketing, product, and executive teams can trust — and a measurable lift in campaign performance that comes from finally knowing what works.',
    ],
    process: [
      { step: 1, title: 'Tracking Audit', description: 'Review your current analytics setup, identify data gaps, broken tags, and attribution blind spots across every channel.' },
      { step: 2, title: 'Measurement Plan', description: 'Define KPIs, event taxonomy, data-layer specifications, and a conversion framework aligned with your business goals.' },
      { step: 3, title: 'Implementation', description: 'Deploy GA4 properties, GTM containers, server-side endpoints, enhanced conversions, and custom event tracking.' },
      { step: 4, title: 'QA & Validation', description: 'Run end-to-end testing with debug tools, compare data across platforms, and validate conversion accuracy.' },
      { step: 5, title: 'Dashboards & Handoff', description: 'Build real-time dashboards in Looker Studio, document every configuration, and train your team on the new setup.' },
    ],
    deliverables: [
      'Full tracking audit report with gap analysis',
      'Measurement plan & event taxonomy document',
      'GA4 property configuration & custom events',
      'Google Tag Manager container setup (web + server)',
      'Server-side tracking deployment',
      'Enhanced conversion tracking for Google Ads',
      'Meta Conversions API integration',
      'Cross-domain tracking configuration',
      'Looker Studio real-time dashboard',
      'Technical documentation & team training',
    ],
    pricing: [
      {
        name: 'Starter',
        price: '$500',
        description: 'Essential tracking for small sites and landing pages.',
        features: [
          { text: 'GA4 setup & configuration', included: true },
          { text: 'GTM container with core tags', included: true },
          { text: 'Up to 10 custom events', included: true },
          { text: 'Basic conversion tracking', included: true },
          { text: 'One Looker Studio dashboard', included: true },
          { text: 'Server-side tracking', included: false },
          { text: 'Enhanced conversions', included: false },
          { text: 'Attribution modeling', included: false },
        ],
      },
      {
        name: 'Professional',
        price: '$1,200',
        description: 'Complete measurement stack for growing businesses.',
        highlighted: true,
        features: [
          { text: 'Everything in Starter', included: true },
          { text: 'Server-side GTM container', included: true },
          { text: 'Up to 30 custom events', included: true },
          { text: 'Enhanced conversions (Google + Meta)', included: true },
          { text: 'Cross-domain tracking', included: true },
          { text: 'Custom attribution model', included: true },
          { text: 'Three Looker Studio dashboards', included: true },
          { text: 'Dedicated QA & documentation', included: true },
        ],
      },
      {
        name: 'Enterprise',
        price: '$2,500',
        description: 'Advanced data architecture for high-traffic operations.',
        features: [
          { text: 'Everything in Professional', included: true },
          { text: 'BigQuery data pipeline', included: true },
          { text: 'Unlimited custom events', included: true },
          { text: 'Multi-property GA4 architecture', included: true },
          { text: 'Consent-mode implementation', included: true },
          { text: 'Custom API integrations', included: true },
          { text: 'Ongoing support (30 days)', included: true },
          { text: 'Team training workshop', included: true },
        ],
      },
    ],
    faqs: [
      { question: 'How long does a full tracking implementation take?', answer: 'A Starter implementation typically takes 3-5 business days. Professional setups run 1-2 weeks, and Enterprise projects with BigQuery pipelines and multi-property architectures take 2-4 weeks depending on site complexity and the number of platforms involved.' },
      { question: 'Will my existing historical data be preserved?', answer: 'Yes. I never delete existing analytics properties. I either upgrade your current GA4 setup in place or create a new property and run parallel tracking so no historical data is lost during the transition.' },
      { question: 'How does server-side tracking help with data accuracy?', answer: 'Server-side tracking sends data from your server rather than the user\'s browser, bypassing ad blockers, ITP restrictions, and cookie limitations. In practice, clients see a 15-30% increase in recorded conversions compared to client-side-only implementations.' },
      { question: 'Do you support platforms beyond Google Analytics?', answer: 'Absolutely. I integrate with Meta Conversions API, TikTok Events API, LinkedIn Insight Tag, Mixpanel, Segment, and most major ad platforms. The core architecture is designed to feed data to any downstream tool.' },
      { question: 'Can you fix my current broken tracking setup?', answer: 'Yes, tracking audits and remediation are a core part of the Starter and Professional tiers. I will identify misfiring tags, duplicate events, incorrect attribution, and data-layer errors and fix them as part of the engagement.' },
      { question: 'What about GDPR and privacy compliance?', answer: 'Every implementation includes consent-mode configuration that respects user privacy preferences. I integrate with popular consent management platforms like Cookiebot, OneTrust, and Complianz to ensure your tracking is fully compliant with GDPR, CCPA, and other regulations.' },
    ],
    relatedSlugs: ['campaign-optimization', 'automation-n8n', 'martech-consulting'],
  },

  'automation-n8n': {
    title: 'Automation with n8n',
    category: 'Workflow Automation',
    description:
      'Eliminate repetitive manual tasks with intelligent n8n workflows, Zapier integrations, and custom API automations that connect your entire marketing and sales stack seamlessly.',
    overview: [
      'Every hour your team spends copying data between spreadsheets, manually routing leads, or sending repetitive follow-up emails is an hour not spent on strategy, creativity, and growth. I build custom automation workflows using n8n — the powerful open-source automation platform — alongside Zapier and direct API integrations to connect your CRM, email platform, ad accounts, project management tools, and databases into a single, self-running ecosystem. The result is fewer human errors, faster response times, and a marketing operation that scales without proportionally scaling headcount.',
      'My automation services cover the full spectrum of marketing and sales operations. On the lead management side, I design workflows that capture leads from forms, ads, and chatbots; enrich them with third-party data; score them based on behavior and fit; and route them to the right sales rep within seconds — not hours. For email marketing, I build trigger-based sequences that respond to user actions in real time, from abandoned-cart recovery to post-purchase onboarding. On the reporting side, I automate data aggregation from Google Ads, Meta, CRM, and analytics platforms into unified dashboards that update themselves daily.',
      'What sets my approach apart is durability and maintainability. I do not just build workflows that work today — I document every automation, add error-handling and retry logic, set up monitoring alerts, and design modular architectures so your team can extend the system without rebuilding from scratch. Whether you are a lean startup looking to automate lead follow-up or an established business needing a complex multi-step orchestration, I deliver automations that pay for themselves within weeks.',
    ],
    process: [
      { step: 1, title: 'Workflow Discovery', description: 'Map your current manual processes, identify automation opportunities, and prioritize by time saved and revenue impact.' },
      { step: 2, title: 'Architecture Design', description: 'Design workflow blueprints with triggers, logic branches, error handling, and integration points for every automation.' },
      { step: 3, title: 'Build & Integrate', description: 'Develop workflows in n8n or Zapier, connect APIs, configure webhooks, and wire up your full tool stack.' },
      { step: 4, title: 'Test & Monitor', description: 'Run end-to-end tests with real data, set up error alerts and logging, and validate output accuracy across every path.' },
      { step: 5, title: 'Launch & Optimize', description: 'Deploy to production, monitor for 2 weeks, optimize performance, and hand off with complete documentation.' },
    ],
    deliverables: [
      'Process audit & automation opportunity map',
      'Workflow architecture diagrams',
      'Custom n8n workflow builds',
      'CRM automation (lead routing & scoring)',
      'Email sequence automation triggers',
      'API integrations between marketing tools',
      'Webhook configuration & data mapping',
      'Error-handling & retry logic',
      'Monitoring dashboard & alert setup',
      'Full documentation & team walkthrough',
    ],
    pricing: [
      {
        name: 'Starter',
        price: '$800',
        description: 'Automate your first critical workflows.',
        features: [
          { text: 'Up to 3 automation workflows', included: true },
          { text: 'Process audit & prioritization', included: true },
          { text: 'Basic CRM integration', included: true },
          { text: 'Error handling included', included: true },
          { text: 'Documentation', included: true },
          { text: 'Custom API integrations', included: false },
          { text: 'Advanced lead scoring', included: false },
          { text: 'Ongoing support', included: false },
        ],
      },
      {
        name: 'Professional',
        price: '$1,800',
        description: 'Full marketing automation stack for scaling teams.',
        highlighted: true,
        features: [
          { text: 'Everything in Starter', included: true },
          { text: 'Up to 8 automation workflows', included: true },
          { text: 'Advanced lead routing & scoring', included: true },
          { text: 'Multi-tool API integrations', included: true },
          { text: 'Email sequence automation', included: true },
          { text: 'Monitoring & alert dashboard', included: true },
          { text: '2-week post-launch support', included: true },
          { text: 'Team training session', included: true },
        ],
      },
      {
        name: 'Enterprise',
        price: '$3,500',
        description: 'Complex orchestration for data-heavy operations.',
        features: [
          { text: 'Everything in Professional', included: true },
          { text: 'Unlimited workflows', included: true },
          { text: 'Custom API development', included: true },
          { text: 'Database integrations (SQL/NoSQL)', included: true },
          { text: 'Multi-step orchestration pipelines', included: true },
          { text: 'Self-hosted n8n setup', included: true },
          { text: '30-day post-launch support', included: true },
          { text: 'Priority Slack/email support', included: true },
        ],
      },
    ],
    faqs: [
      { question: 'Why n8n over Zapier or Make?', answer: 'n8n is open-source, self-hostable, and far more cost-effective at scale. It supports complex branching logic, sub-workflows, and custom code nodes that Zapier simply cannot match. That said, I also build on Zapier and Make when they are a better fit for the client\'s team and budget.' },
      { question: 'How many hours per week can automation save my team?', answer: 'Most clients save 10-20 hours per week on manual data entry, lead routing, and report generation alone. One e-commerce client reduced their order processing time from 45 minutes to under 2 minutes per order.' },
      { question: 'What tools can you integrate?', answer: 'I integrate with HubSpot, Salesforce, Pipedrive, Mailchimp, ActiveCampaign, Slack, Google Sheets, Airtable, Notion, Stripe, Shopify, WooCommerce, Google Ads, Meta Ads, and hundreds of other tools via API or webhook.' },
      { question: 'What happens if a workflow breaks?', answer: 'Every workflow includes error-handling logic and retry mechanisms. I also set up monitoring alerts via Slack or email so your team is notified immediately if any automation fails, along with detailed error logs for troubleshooting.' },
      { question: 'Can you automate our reporting?', answer: 'Yes, automated reporting is one of the most popular use cases. I build workflows that pull data from your ad platforms, CRM, and analytics tools, aggregate it, and push formatted reports to Slack, email, or Google Sheets on a daily or weekly schedule.' },
      { question: 'Do you offer ongoing maintenance?', answer: 'The Enterprise tier includes 30 days of post-launch support. Beyond that, I offer monthly retainer packages for ongoing monitoring, optimization, and new workflow development starting at $500/month.' },
    ],
    relatedSlugs: ['tracking-analytics', 'email-crm-systems', 'martech-consulting'],
  },

  'wordpress-development': {
    title: 'Modern WordPress Dev',
    category: 'Web Development',
    description:
      'High-performance WordPress websites built with Elementor, custom themes, WooCommerce, and speed optimization — designed to rank on search engines and convert visitors into customers.',
    overview: [
      'Your website is the single most important asset in your digital marketing ecosystem. It is the destination where every ad click, email link, and social post ultimately sends your prospects — and if it loads slowly, looks dated, or fails to guide visitors toward a conversion, you are leaving money on the table. I build modern WordPress websites using Elementor Pro and custom theme development that are engineered from the ground up for speed, search visibility, and conversion optimization. Every site I deliver scores 90+ on Google PageSpeed Insights, is fully responsive across all devices, and follows a logical information architecture that guides visitors from awareness to action.',
      'My development process starts with strategy, not code. I work with you to define your ideal customer journey, map out conversion funnels, and plan content hierarchy before a single pixel is designed. The build phase combines Elementor Pro for rapid, visually stunning page creation with custom PHP and CSS where needed for functionality that page builders cannot deliver out of the box. For e-commerce clients, I set up WooCommerce with optimized product pages, streamlined checkout flows, and integrations with payment gateways, shipping providers, and inventory management systems. Every site includes structured data markup (schema.org), XML sitemaps, and a technical SEO foundation that gives you a head start in organic search rankings.',
      'Performance is not an afterthought — it is built into every layer of the stack. I configure server-level caching, optimize images with next-gen formats like WebP and AVIF, implement lazy loading, minify CSS and JavaScript, and select hosting environments (Cloudways, Kinsta, or WP Engine) that deliver sub-second time-to-first-byte globally. Post-launch, I provide documentation, CMS training, and optional maintenance packages so your team can update content confidently without breaking anything.',
    ],
    process: [
      { step: 1, title: 'Strategy & Wireframes', description: 'Define site goals, user flows, content hierarchy, and wireframe key pages before any design begins.' },
      { step: 2, title: 'Design & Prototyping', description: 'Create high-fidelity page designs in Elementor with your brand guidelines, fonts, and imagery.' },
      { step: 3, title: 'Development & Build', description: 'Build out all pages, custom functionality, forms, integrations, and WooCommerce setup if applicable.' },
      { step: 4, title: 'Speed & SEO Optimization', description: 'Optimize Core Web Vitals, implement caching, structured data, XML sitemaps, and image compression.' },
      { step: 5, title: 'Launch & Training', description: 'Deploy to production hosting, run final QA, and train your team on managing content and the CMS.' },
    ],
    deliverables: [
      'Custom WordPress theme or Elementor Pro build',
      'Responsive design for all breakpoints',
      'WooCommerce store setup (if applicable)',
      'Contact forms & lead capture integration',
      'Google PageSpeed score 90+ optimization',
      'Technical SEO foundation (schema, sitemaps, meta)',
      'Security hardening & SSL configuration',
      'Server-level caching & CDN setup',
      'CMS training & documentation',
      'Post-launch support (14 days)',
    ],
    pricing: [
      {
        name: 'Starter',
        price: '$1,500',
        description: 'Professional site for small businesses and personal brands.',
        features: [
          { text: 'Up to 5 pages', included: true },
          { text: 'Elementor Pro design', included: true },
          { text: 'Mobile responsive', included: true },
          { text: 'Contact form integration', included: true },
          { text: 'Basic SEO setup', included: true },
          { text: 'Speed optimization', included: true },
          { text: 'WooCommerce', included: false },
          { text: 'Custom functionality', included: false },
        ],
      },
      {
        name: 'Professional',
        price: '$3,000',
        description: 'Feature-rich site built for lead generation and growth.',
        highlighted: true,
        features: [
          { text: 'Everything in Starter', included: true },
          { text: 'Up to 15 pages', included: true },
          { text: 'Custom theme development', included: true },
          { text: 'Blog & content system', included: true },
          { text: 'CRM & email integration', included: true },
          { text: 'Advanced SEO & schema markup', included: true },
          { text: 'Analytics & tracking setup', included: true },
          { text: '14-day post-launch support', included: true },
        ],
      },
      {
        name: 'Enterprise',
        price: '$6,000',
        description: 'Complex site or WooCommerce store with custom functionality.',
        features: [
          { text: 'Everything in Professional', included: true },
          { text: 'Unlimited pages', included: true },
          { text: 'WooCommerce full setup', included: true },
          { text: 'Payment gateway integration', included: true },
          { text: 'Custom plugin development', included: true },
          { text: 'Multi-language support', included: true },
          { text: 'Premium hosting setup', included: true },
          { text: '30-day post-launch support', included: true },
        ],
      },
    ],
    faqs: [
      { question: 'How long does it take to build a WordPress site?', answer: 'Starter sites typically take 1-2 weeks, Professional builds run 2-4 weeks, and Enterprise projects with WooCommerce or custom functionality take 4-8 weeks. Timelines depend on content readiness and feedback turnaround.' },
      { question: 'Do I need to provide the content and images?', answer: 'Ideally, yes — you know your business best. However, I can provide copywriting guidance, stock image sourcing, and content structure recommendations. For full content creation, I offer it as an add-on service.' },
      { question: 'Will the site be easy for my team to update?', answer: 'Absolutely. Elementor Pro provides a visual drag-and-drop editor that requires zero coding knowledge. I also provide a CMS training session and written documentation so your team can confidently manage content, blog posts, and product listings.' },
      { question: 'What hosting do you recommend?', answer: 'I recommend Cloudways, Kinsta, or WP Engine depending on your budget and traffic volume. All three deliver excellent performance, security, and scalability. I handle the full hosting setup and migration as part of the project.' },
      { question: 'Can you redesign my existing WordPress site?', answer: 'Yes. I regularly redesign and rebuild existing WordPress sites while preserving SEO equity, redirecting old URLs, and migrating content. I ensure zero downtime during the switch with a staging-to-production deployment process.' },
      { question: 'Do you offer ongoing maintenance after launch?', answer: 'Yes, I offer monthly maintenance packages that include plugin updates, security monitoring, daily backups, performance checks, and minor content updates starting at $150/month.' },
    ],
    relatedSlugs: ['seo-content-strategy', 'tracking-analytics', 'campaign-optimization'],
  },

  'campaign-optimization': {
    title: 'Campaign Optimization',
    category: 'Paid Advertising',
    description:
      'Data-driven management of Google Ads, Meta Ads, and LinkedIn Ads campaigns — with scientific A/B testing, retargeting, and relentless ROAS optimization to maximize every ad dollar.',
    overview: [
      'Running paid ads without proper optimization is like burning cash — you might get some results, but you will never know how much you are wasting. I manage and optimize advertising campaigns across Google Ads, Meta Ads (Facebook and Instagram), and LinkedIn Ads using a scientific, data-first approach that focuses on one metric above all: profitable return on ad spend. Every campaign I build is structured for testability, with clear hypotheses, controlled variables, and systematic iteration that compounds performance gains week over week. From keyword-level bid adjustments in Google Search to creative rotation in Meta, I optimize at the granular level where the biggest wins hide.',
      'My campaign management covers the entire paid media lifecycle. I start with a thorough account audit and competitive analysis, then build or restructure campaigns with proper audience segmentation, ad group theming, and conversion tracking. For Google Ads, that means tightly themed search campaigns, Performance Max configurations, and remarketing lists for search ads (RLSA). For Meta, it means full-funnel campaign architectures — prospecting with lookalike audiences at the top, engagement-based retargeting in the middle, and dynamic product ads or offer campaigns at the bottom. LinkedIn campaigns are structured around job title, company size, and industry targeting for B2B lead generation.',
      'What truly differentiates my approach is the testing framework. I run continuous A/B and multivariate tests on ad copy, creative assets, landing pages, audiences, and bidding strategies — measuring statistical significance before making scaling decisions. Every client receives transparent weekly or bi-weekly reports with clear metrics: cost per acquisition, ROAS, click-through rates, and quality scores alongside actionable recommendations. The goal is not just clicks and impressions — it is revenue growth you can trace directly back to your ad investment.',
    ],
    process: [
      { step: 1, title: 'Account Audit', description: 'Deep analysis of existing campaigns, wasted spend, audience overlap, and conversion tracking accuracy.' },
      { step: 2, title: 'Strategy & Structure', description: 'Develop a full-funnel campaign architecture with audience segmentation, bid strategy, and budget allocation.' },
      { step: 3, title: 'Creative & Copy', description: 'Write ad copy, develop creative briefs, and build landing page recommendations for maximum Quality Score.' },
      { step: 4, title: 'Launch & Test', description: 'Launch campaigns with A/B tests on headlines, creatives, audiences, and bidding strategies from day one.' },
      { step: 5, title: 'Optimize & Scale', description: 'Weekly optimization of bids, budgets, negatives, and creative rotation — scaling winners and cutting losers.' },
    ],
    deliverables: [
      'Comprehensive account audit report',
      'Full-funnel campaign strategy document',
      'Campaign build & structure setup',
      'Ad copy & creative direction',
      'Conversion tracking verification',
      'A/B testing framework & schedule',
      'Retargeting & remarketing setup',
      'Negative keyword management',
      'Weekly/bi-weekly performance reports',
      'Monthly strategy review calls',
    ],
    pricing: [
      {
        name: 'Starter',
        price: '$800/mo',
        description: 'Single-platform management for emerging brands.',
        features: [
          { text: 'One ad platform (Google or Meta)', included: true },
          { text: 'Up to $5K monthly ad spend', included: true },
          { text: 'Campaign setup & optimization', included: true },
          { text: 'Conversion tracking setup', included: true },
          { text: 'Monthly performance report', included: true },
          { text: 'A/B creative testing', included: false },
          { text: 'Retargeting campaigns', included: false },
          { text: 'LinkedIn Ads', included: false },
        ],
      },
      {
        name: 'Professional',
        price: '$1,500/mo',
        description: 'Multi-platform campaigns for growth-stage businesses.',
        highlighted: true,
        features: [
          { text: 'Everything in Starter', included: true },
          { text: 'Two ad platforms', included: true },
          { text: 'Up to $20K monthly ad spend', included: true },
          { text: 'Full-funnel campaign structure', included: true },
          { text: 'A/B testing framework', included: true },
          { text: 'Retargeting & remarketing', included: true },
          { text: 'Bi-weekly reports & strategy calls', included: true },
          { text: 'Landing page recommendations', included: true },
        ],
      },
      {
        name: 'Enterprise',
        price: '$3,000/mo',
        description: 'Full-service paid media for high-growth operations.',
        features: [
          { text: 'Everything in Professional', included: true },
          { text: 'All major ad platforms', included: true },
          { text: 'Unlimited ad spend management', included: true },
          { text: 'Advanced audience strategies', included: true },
          { text: 'Dynamic creative optimization', included: true },
          { text: 'Custom attribution modeling', included: true },
          { text: 'Weekly reports & strategy calls', included: true },
          { text: 'Dedicated Slack channel', included: true },
        ],
      },
    ],
    faqs: [
      { question: 'What return on ad spend (ROAS) can I expect?', answer: 'Results vary by industry and offer, but most clients achieve 3-6x ROAS within 90 days. E-commerce brands often see 5-10x, while B2B lead-gen campaigns typically target a cost-per-lead that delivers a positive customer lifetime value ratio. I set realistic benchmarks during the audit phase.' },
      { question: 'How quickly will I see results from paid ads?', answer: 'Paid ads deliver traffic immediately, but optimization takes time. You will typically see initial performance data within the first week, meaningful optimization gains by week 3-4, and compounding improvements over the first 90 days as we accumulate conversion data and refine targeting.' },
      { question: 'Is the ad spend included in your management fee?', answer: 'No, my management fee is separate from your ad spend budget. You pay the ad platforms directly. This keeps things transparent — you always know exactly how much goes to media versus management.' },
      { question: 'Do you create the ad visuals and videos?', answer: 'I write all ad copy and provide detailed creative briefs with specifications, sizing, and messaging direction. For visual production, I collaborate with designers or can recommend creative partners. Basic static ad creation is included in Professional and Enterprise tiers.' },
      { question: 'Can you take over my existing campaigns?', answer: 'Absolutely. I start with a full audit of your existing account, preserve what is working, restructure what is not, and implement proper tracking before making optimization changes. There is no need to start from scratch.' },
      { question: 'What is the minimum commitment period?', answer: 'I recommend a minimum 3-month commitment because paid media optimization is cumulative — the algorithm needs data, and meaningful A/B tests need time to reach statistical significance. That said, there are no long-term contracts; you can cancel with 30 days notice.' },
    ],
    relatedSlugs: ['tracking-analytics', 'seo-content-strategy', 'social-media-marketing'],
  },

  'seo-content-strategy': {
    title: 'SEO & Content Strategy',
    category: 'Organic Growth',
    description:
      'Data-driven technical SEO, strategic keyword research, and high-quality content creation that ranks on page one, builds domain authority, and converts organic visitors into leads and customers.',
    overview: [
      'Organic search is the highest-ROI marketing channel for most businesses — but only when it is executed with technical precision and strategic intent. I deliver comprehensive SEO services that cover every layer of the discipline: technical infrastructure, on-page optimization, content creation, and off-page authority building. My approach starts with a detailed technical SEO audit that identifies crawl errors, Core Web Vitals issues, indexation problems, site architecture flaws, and structured data gaps. Fixing these foundational issues alone often produces measurable ranking improvements within weeks, because you are removing the barriers that prevent Google from properly understanding and ranking your content.',
      'On the strategic side, I conduct deep keyword research using Ahrefs, SEMrush, and Google Search Console data to identify high-value keyword opportunities at every stage of the buyer journey — from informational queries that build awareness to transactional keywords that capture ready-to-buy intent. Each keyword is mapped to a specific page or content piece within a comprehensive content strategy that ensures topical authority and internal linking cohesion. I then create or optimize content that satisfies search intent, includes semantic keyword variations, and is structured with proper heading hierarchy, schema markup, and internal links that pass authority to your most important pages.',
      'Link building and off-page SEO complete the picture. I develop white-hat backlink strategies through digital PR, guest posting on relevant industry publications, broken link building, and HARO outreach. Every backlink is earned from topically relevant, high-authority domains — no PBNs, link farms, or shortcuts that risk penalties. Monthly reporting includes keyword ranking movements, organic traffic growth, backlink acquisition, and conversion metrics tied to specific content pieces so you can see exactly which efforts drive revenue.',
    ],
    process: [
      { step: 1, title: 'Technical SEO Audit', description: 'Crawl your site, analyze Core Web Vitals, indexation, site architecture, schema, and identify every technical issue.' },
      { step: 2, title: 'Keyword Research', description: 'Identify high-value keyword opportunities across the buyer journey using Ahrefs, SEMrush, and Search Console data.' },
      { step: 3, title: 'Content Strategy', description: 'Build a content calendar mapping keywords to pages, define content briefs, and plan internal linking architecture.' },
      { step: 4, title: 'On-Page Optimization', description: 'Optimize existing pages — titles, meta descriptions, headings, content, schema markup, and internal links.' },
      { step: 5, title: 'Link Building & Reporting', description: 'Execute white-hat backlink campaigns and deliver monthly reports on rankings, traffic, and conversions.' },
    ],
    deliverables: [
      'Comprehensive technical SEO audit (50+ checkpoints)',
      'Keyword research database (500+ keywords)',
      'Content strategy & editorial calendar',
      'On-page optimization for priority pages',
      'Schema markup implementation',
      'Internal linking strategy & execution',
      'Monthly link building outreach',
      'XML sitemap & robots.txt optimization',
      'Competitor backlink gap analysis',
      'Monthly ranking & traffic reports',
    ],
    pricing: [
      {
        name: 'Starter',
        price: '$600/mo',
        description: 'SEO foundations for businesses starting their organic journey.',
        features: [
          { text: 'Technical SEO audit & fixes', included: true },
          { text: 'Keyword research (100 keywords)', included: true },
          { text: 'On-page optimization (5 pages/mo)', included: true },
          { text: 'Monthly ranking report', included: true },
          { text: 'Basic schema markup', included: true },
          { text: 'Content creation', included: false },
          { text: 'Link building', included: false },
          { text: 'Competitor monitoring', included: false },
        ],
      },
      {
        name: 'Professional',
        price: '$1,200/mo',
        description: 'Full SEO program with content and link building.',
        highlighted: true,
        features: [
          { text: 'Everything in Starter', included: true },
          { text: 'Keyword research (300+ keywords)', included: true },
          { text: 'On-page optimization (10 pages/mo)', included: true },
          { text: '2 SEO blog articles per month', included: true },
          { text: 'Monthly link building (5 links)', included: true },
          { text: 'Content strategy & editorial calendar', included: true },
          { text: 'Local SEO optimization', included: true },
          { text: 'Bi-weekly strategy calls', included: true },
        ],
      },
      {
        name: 'Enterprise',
        price: '$2,500/mo',
        description: 'Aggressive SEO growth for competitive industries.',
        features: [
          { text: 'Everything in Professional', included: true },
          { text: 'Unlimited keyword research', included: true },
          { text: 'On-page optimization (20+ pages/mo)', included: true },
          { text: '4 SEO articles per month', included: true },
          { text: 'Aggressive link building (15+ links)', included: true },
          { text: 'Competitor monitoring dashboard', included: true },
          { text: 'Content refresh & optimization', included: true },
          { text: 'Weekly strategy calls', included: true },
        ],
      },
    ],
    faqs: [
      { question: 'How long does it take to see SEO results?', answer: 'SEO is a long-term investment. Technical fixes and on-page optimizations can show ranking movements within 2-4 weeks. Content and link building typically produce meaningful traffic growth in 3-6 months, with compounding results over 6-12 months. The exact timeline depends on your domain authority, competition level, and content velocity.' },
      { question: 'Do you guarantee first-page rankings?', answer: 'No ethical SEO professional can guarantee specific rankings because Google\'s algorithm considers hundreds of factors. What I guarantee is a systematic, data-driven approach that consistently produces measurable organic growth. Most clients see 50-200% organic traffic increases within 6-12 months.' },
      { question: 'Will you write the content or do I need to provide it?', answer: 'Professional and Enterprise tiers include content creation — I write SEO-optimized blog articles with proper keyword targeting, internal links, and schema markup. For Starter clients, I provide detailed content briefs and optimization guidelines your team can follow.' },
      { question: 'What tools do you use for SEO?', answer: 'My primary toolkit includes Ahrefs for backlink analysis and keyword research, SEMrush for competitive intelligence, Screaming Frog for technical audits, Google Search Console for performance data, Surfer SEO for content optimization, and custom Google Sheets models for tracking and reporting.' },
      { question: 'Can you help with local SEO?', answer: 'Yes, local SEO is included in Professional and Enterprise tiers. This covers Google Business Profile optimization, local keyword targeting, NAP consistency audits, local schema markup, and citation building across relevant directories.' },
      { question: 'What if I already have an SEO agency?', answer: 'I am happy to work alongside existing agencies or in-house teams. Many clients engage me for a specific scope — like a technical audit, content strategy, or link building — that complements their existing efforts. I can also provide a second-opinion audit to identify gaps in your current SEO program.' },
    ],
    relatedSlugs: ['wordpress-development', 'campaign-optimization', 'social-media-marketing'],
  },

  'martech-consulting': {
    title: 'MarTech Consulting',
    category: 'Marketing Technology',
    description:
      'Expert guidance to audit, select, integrate, and optimize your marketing technology stack — from CRM setup and data migration to team training and vendor management.',
    overview: [
      'The average marketing team uses dozens of software tools, yet most are underutilized, poorly integrated, or outright redundant. The result is fragmented data, manual workarounds, and a tech stack that costs more than it delivers. My MarTech consulting service cuts through the noise and helps you build a lean, integrated technology ecosystem where every tool serves a clear purpose, data flows seamlessly between systems, and your team actually uses the features they are paying for. Whether you are a startup choosing your first CRM or an enterprise consolidating a sprawling tool landscape, I bring vendor-agnostic expertise and hands-on implementation support.',
      'The engagement begins with a thorough tech stack audit where I inventory every marketing tool, map data flows, identify integration gaps, and calculate the true total cost of ownership including underused licenses. From there, I develop a requirements specification based on your business processes, growth plans, and team capabilities — not vendor marketing materials. If new tools are needed, I run structured vendor evaluations with weighted scorecards, arrange demos, and negotiate contracts leveraging my industry relationships. The recommendation is always what fits your business, not what pays the highest referral commission.',
      'Implementation is where most MarTech projects fail, and it is where I add the most value. I design integration architectures showing exactly how data will flow between your CRM, email platform, analytics, ad accounts, and other tools. I configure the systems, build automations, migrate historical data, and train your team on proper usage. The result is a marketing technology stack that is documented, maintainable, and built to scale — one that gives you a single source of truth for customer data and eliminates the manual data shuffling that wastes your team\'s time.',
    ],
    process: [
      { step: 1, title: 'Tech Stack Audit', description: 'Inventory all current marketing tools, map data flows, identify redundancies, and calculate total cost of ownership.' },
      { step: 2, title: 'Requirements Analysis', description: 'Define business requirements, team capabilities, integration needs, and growth projections for tool selection.' },
      { step: 3, title: 'Vendor Evaluation', description: 'Research, demo, and score potential tools using weighted evaluation scorecards tailored to your priorities.' },
      { step: 4, title: 'Architecture & Integration', description: 'Design integration architecture, configure tools, build data pipelines, and migrate historical data.' },
      { step: 5, title: 'Training & Handoff', description: 'Train your team on proper usage, deliver documentation, and provide ongoing advisory support.' },
    ],
    deliverables: [
      'Current tech stack audit report',
      'Total cost of ownership analysis',
      'Business requirements specification',
      'Vendor comparison scorecards',
      'Integration architecture diagram',
      'Tool configuration & setup',
      'Data migration execution',
      'Implementation roadmap',
      'Team training workshops',
      'Documentation & standard operating procedures',
    ],
    pricing: [
      {
        name: 'Starter',
        price: '$1,000',
        description: 'Tech stack audit and strategic recommendations.',
        features: [
          { text: 'Full tech stack audit', included: true },
          { text: 'Cost of ownership analysis', included: true },
          { text: 'Tool recommendations report', included: true },
          { text: 'Integration architecture plan', included: true },
          { text: '2-week engagement', included: true },
          { text: 'Vendor evaluation scorecards', included: false },
          { text: 'Hands-on implementation', included: false },
          { text: 'Team training', included: false },
        ],
      },
      {
        name: 'Professional',
        price: '$2,500',
        description: 'Full evaluation and guided implementation.',
        highlighted: true,
        features: [
          { text: 'Everything in Starter', included: true },
          { text: 'Detailed vendor evaluation', included: true },
          { text: 'Contract negotiation support', included: true },
          { text: 'Guided implementation', included: true },
          { text: 'CRM configuration', included: true },
          { text: 'Data migration (one platform)', included: true },
          { text: 'Team training (2 sessions)', included: true },
          { text: '4-week engagement', included: true },
        ],
      },
      {
        name: 'Enterprise',
        price: '$5,000',
        description: 'Complete stack overhaul with hands-on implementation.',
        features: [
          { text: 'Everything in Professional', included: true },
          { text: 'Multi-platform data migration', included: true },
          { text: 'Custom integration development', included: true },
          { text: 'Automation workflow setup', included: true },
          { text: 'Comprehensive team training', included: true },
          { text: 'Vendor management support', included: true },
          { text: 'Ongoing advisory (3 months)', included: true },
          { text: 'Priority support channel', included: true },
        ],
      },
    ],
    faqs: [
      { question: 'Is MarTech consulting only for large companies?', answer: 'Not at all. Some of my most impactful engagements are with startups and small businesses who want to get their stack right from the beginning, avoiding costly migrations later. Whether you have 3 tools or 30, there is always room to optimize.' },
      { question: 'Will you recommend the most expensive tools?', answer: 'No. My recommendations are vendor-agnostic and based entirely on your business requirements, team size, and budget. I frequently recommend free or lower-cost alternatives when they genuinely fit better. I do not accept referral commissions from vendors.' },
      { question: 'How do you handle data migration between platforms?', answer: 'I follow a structured migration process: data audit, field mapping, cleansing, test migration, validation, and final cutover. Historical data, custom fields, and relationships are preserved. I run parallel systems during transition to ensure zero data loss.' },
      { question: 'Can you help us negotiate vendor contracts?', answer: 'Yes, included in Professional and Enterprise tiers. I leverage my knowledge of standard pricing, competitor offerings, and negotiation tactics to help you secure better terms, volume discounts, and extended trial periods.' },
      { question: 'What CRM platforms do you work with?', answer: 'I have deep expertise with HubSpot, Salesforce, Pipedrive, Zoho CRM, and ActiveCampaign. I also work with industry-specific CRMs and can evaluate any platform against your requirements.' },
      { question: 'Do you provide ongoing support after the project?', answer: 'The Enterprise tier includes 3 months of ongoing advisory support. For other tiers, I offer optional retainer packages for continued optimization, training, and vendor management starting at $500/month.' },
    ],
    relatedSlugs: ['automation-n8n', 'email-crm-systems', 'tracking-analytics'],
  },

  'social-media-marketing': {
    title: 'Social Media Marketing',
    category: 'Social & Community',
    description:
      'Strategic social media marketing that builds brand authority, grows engaged communities, and drives measurable business results through organic content, paid campaigns, and influencer partnerships.',
    overview: [
      'Social media is no longer optional — it is where your customers discover brands, research solutions, and decide who to trust. But posting sporadically without a strategy is worse than not posting at all; it signals to your audience that your brand lacks direction. I deliver comprehensive social media marketing that combines strategic content planning, professional content creation, active community management, and paid social campaigns into a cohesive program that builds real brand equity and drives measurable business outcomes. Every post, story, and campaign ties back to your business objectives, whether that is lead generation, e-commerce sales, brand awareness, or thought leadership.',
      'My content strategy starts with audience research — understanding not just demographics but psychographics, content consumption habits, and the specific pain points your audience discusses on each platform. I then develop platform-specific content calendars that balance educational content (building authority), engagement content (sparking conversations), and promotional content (driving conversions) in a ratio that keeps your audience growing and engaged. Content formats are tailored to each platform: carousels and thought leadership posts for LinkedIn, Reels and Stories for Instagram, short-form video for TikTok, and community-building posts for Facebook. Every piece of content is designed to stop the scroll, deliver value, and reinforce your brand positioning.',
      'Beyond organic growth, I manage paid social campaigns that amplify your best-performing content, retarget website visitors, and reach new audiences through lookalike targeting. I also coordinate influencer outreach and partnerships when relevant — identifying creators whose audience aligns with your ideal customer profile and negotiating collaborations that deliver authentic exposure. Monthly analytics reports track follower growth, engagement rates, reach, website traffic from social, and most importantly, conversions and revenue attributed to social media efforts.',
    ],
    process: [
      { step: 1, title: 'Audit & Research', description: 'Analyze your current social presence, competitor activity, audience demographics, and content performance data.' },
      { step: 2, title: 'Strategy Development', description: 'Build platform-specific content strategies with brand voice guidelines, content pillars, and posting schedules.' },
      { step: 3, title: 'Content Creation', description: 'Produce scroll-stopping posts, graphics, short-form videos, carousels, stories, and copy for every platform.' },
      { step: 4, title: 'Community Management', description: 'Engage with your audience through comments, DMs, proactive outreach, and reputation monitoring.' },
      { step: 5, title: 'Analytics & Optimization', description: 'Track performance metrics, identify top-performing content, and iterate strategy based on real data.' },
    ],
    deliverables: [
      'Social media audit & competitor analysis',
      'Platform-specific content strategy',
      'Monthly content calendar',
      'Custom post creation (graphics & copy)',
      'Short-form video production',
      'Community engagement management',
      'Paid social campaign management',
      'Influencer outreach & coordination',
      'Hashtag & trending topic research',
      'Monthly analytics & performance report',
    ],
    pricing: [
      {
        name: 'Starter',
        price: '$500/mo',
        description: 'Essential social presence for emerging brands.',
        features: [
          { text: '2 platforms managed', included: true },
          { text: '12 posts per month', included: true },
          { text: 'Content calendar', included: true },
          { text: 'Basic community management', included: true },
          { text: 'Monthly analytics report', included: true },
          { text: 'Short-form video', included: false },
          { text: 'Paid social campaigns', included: false },
          { text: 'Influencer outreach', included: false },
        ],
      },
      {
        name: 'Professional',
        price: '$1,000/mo',
        description: 'Active social growth with content and community.',
        highlighted: true,
        features: [
          { text: 'Everything in Starter', included: true },
          { text: '3 platforms managed', included: true },
          { text: '20 posts per month', included: true },
          { text: '4 short-form videos/month', included: true },
          { text: 'Active community management', included: true },
          { text: 'Paid social campaign setup', included: true },
          { text: 'Story/Reel creation', included: true },
          { text: 'Bi-weekly strategy calls', included: true },
        ],
      },
      {
        name: 'Enterprise',
        price: '$2,000/mo',
        description: 'Full-service social media for maximum brand impact.',
        features: [
          { text: 'Everything in Professional', included: true },
          { text: '5 platforms managed', included: true },
          { text: '30+ posts per month', included: true },
          { text: '8 short-form videos/month', included: true },
          { text: 'Full community management', included: true },
          { text: 'Paid social management', included: true },
          { text: 'Influencer outreach', included: true },
          { text: 'Weekly reports & strategy calls', included: true },
        ],
      },
    ],
    faqs: [
      { question: 'Which social media platforms do you manage?', answer: 'I manage LinkedIn, Instagram, Facebook, TikTok, Twitter/X, Pinterest, and YouTube. The platforms included depend on your tier and where your target audience is most active. I recommend focusing on 2-3 platforms well rather than spreading thin across all of them.' },
      { question: 'Do you create the visual content and videos?', answer: 'Yes. My service includes graphic design for posts and carousels, short-form video creation (Reels, TikTok, Shorts), and story content. For high-production video needs, I partner with videographers and include creative direction and scripting.' },
      { question: 'How do you maintain my brand voice across platforms?', answer: 'I start every engagement with a brand voice workshop where we define your tone, vocabulary, visual style, and messaging pillars. This becomes a documented style guide that ensures consistency across every post, comment, and DM — even as the content is adapted for different platform cultures.' },
      { question: 'Can you manage paid social ads alongside organic content?', answer: 'Absolutely. Professional and Enterprise tiers include paid social campaign management. I boost top-performing organic content, run targeted ad campaigns, and set up retargeting for website visitors — all managed within a unified strategy.' },
      { question: 'What results can I expect from social media marketing?', answer: 'Typical results include 30-100% follower growth in the first 3 months, 2-5x improvement in engagement rates, and measurable increases in website traffic and leads from social. B2B clients on LinkedIn often see the fastest lead generation results, while e-commerce brands benefit from Instagram and TikTok shop integrations.' },
      { question: 'Do I need to approve every post before it goes live?', answer: 'I provide the full content calendar for approval before the month begins. You can review and request changes to any post. Most clients approve the monthly calendar upfront and trust me to handle day-to-day community engagement within the established brand guidelines.' },
    ],
    relatedSlugs: ['campaign-optimization', 'seo-content-strategy', 'email-crm-systems'],
  },

  'email-crm-systems': {
    title: 'Email & CRM Systems',
    category: 'Email & Automation',
    description:
      'Build automated email marketing systems, lead nurturing sequences, and CRM configurations that convert prospects into customers — with precise segmentation, deliverability optimization, and measurable revenue attribution.',
    overview: [
      'Email marketing consistently delivers the highest ROI of any digital channel — $36 for every $1 spent on average — but only when it is built on a well-configured CRM, intelligent segmentation, and automated sequences that deliver the right message at the right time. I design and implement complete email and CRM ecosystems that transform your contact database from a static list into a revenue-generating engine. From initial CRM setup and data migration to advanced automation sequences and deliverability optimization, I handle every layer of the system so your sales and marketing teams can focus on closing deals instead of wrestling with technology.',
      'My CRM configuration goes far beyond basic contact fields. I design custom pipelines, deal stages, lead scoring models, and automated task assignments that reflect your actual sales process — not a generic template. Contact segmentation is built on behavioral data (email opens, link clicks, page visits, form submissions) combined with demographic and firmographic attributes, enabling hyper-targeted messaging that feels personal at any scale. For email marketing, I build trigger-based automation sequences for every stage of the customer lifecycle: welcome series for new subscribers, lead nurturing drips for prospects, abandoned cart recovery for e-commerce, onboarding sequences for new customers, and re-engagement campaigns for dormant contacts.',
      'Deliverability is the invisible foundation that determines whether your emails reach the inbox or the spam folder. I configure SPF, DKIM, and DMARC authentication records, warm up new sending domains, monitor sender reputation scores, and optimize send times, subject lines, and list hygiene practices to maintain consistently high inbox placement rates. Every engagement includes detailed performance reporting: open rates, click-through rates, conversion rates, revenue per email, and list growth metrics — all tied back to your CRM so you can see exactly which emails drive pipeline and revenue.',
    ],
    process: [
      { step: 1, title: 'CRM Audit & Setup', description: 'Audit your existing CRM or set up a new one with custom fields, pipelines, deal stages, and user permissions.' },
      { step: 2, title: 'Data & Segmentation', description: 'Clean, import, and segment your contact database based on behavior, demographics, and engagement history.' },
      { step: 3, title: 'Automation Design', description: 'Design email sequences with triggers, branching logic, and dynamic content for every lifecycle stage.' },
      { step: 4, title: 'Build & Test', description: 'Build email templates, automation workflows, and lead scoring models. Test across devices and email clients.' },
      { step: 5, title: 'Launch & Optimize', description: 'Deploy sequences, monitor deliverability metrics, A/B test subject lines and content, and optimize based on data.' },
    ],
    deliverables: [
      'CRM configuration (pipelines, fields, permissions)',
      'Contact data cleaning & migration',
      'Segmentation strategy & implementation',
      'Lead scoring model setup',
      'Email automation sequences (welcome, nurture, recovery)',
      'Responsive email template design',
      'SPF/DKIM/DMARC authentication setup',
      'Deliverability audit & optimization',
      'A/B testing framework for emails',
      'Performance dashboard & reporting',
    ],
    pricing: [
      {
        name: 'Starter',
        price: '$700',
        description: 'CRM setup and basic email automation.',
        features: [
          { text: 'CRM configuration & setup', included: true },
          { text: 'Contact import & cleaning', included: true },
          { text: 'Basic segmentation', included: true },
          { text: '2 email automation sequences', included: true },
          { text: '3 email templates', included: true },
          { text: 'Lead scoring', included: false },
          { text: 'Deliverability optimization', included: false },
          { text: 'Advanced automation', included: false },
        ],
      },
      {
        name: 'Professional',
        price: '$1,500',
        description: 'Full email system with nurturing and lead scoring.',
        highlighted: true,
        features: [
          { text: 'Everything in Starter', included: true },
          { text: 'Advanced segmentation strategy', included: true },
          { text: 'Lead scoring model', included: true },
          { text: '5 automation sequences', included: true },
          { text: '8 email templates', included: true },
          { text: 'SPF/DKIM/DMARC setup', included: true },
          { text: 'A/B testing framework', included: true },
          { text: 'Performance dashboard', included: true },
        ],
      },
      {
        name: 'Enterprise',
        price: '$3,000',
        description: 'Advanced CRM ecosystem with full lifecycle automation.',
        features: [
          { text: 'Everything in Professional', included: true },
          { text: 'Multi-pipeline CRM setup', included: true },
          { text: 'Unlimited automation sequences', included: true },
          { text: 'Dynamic content personalization', included: true },
          { text: 'Deliverability optimization', included: true },
          { text: 'Custom CRM integrations', included: true },
          { text: 'Team training workshop', included: true },
          { text: '30-day post-launch support', included: true },
        ],
      },
    ],
    faqs: [
      { question: 'Which email and CRM platforms do you work with?', answer: 'I have deep expertise with HubSpot, ActiveCampaign, Mailchimp, Klaviyo, ConvertKit, Brevo (Sendinblue), Salesforce, and Pipedrive. I also configure integrations between any of these platforms and your existing marketing tools.' },
      { question: 'Can you migrate our data from another CRM?', answer: 'Yes, CRM migration is a core part of the service. I handle full data export, cleaning, field mapping, and import — including contacts, deals, custom fields, notes, and activity history. I run parallel systems during transition to ensure zero data loss.' },
      { question: 'How many email sequences do I need?', answer: 'At minimum, every business should have a welcome sequence, a lead nurturing sequence, and a re-engagement sequence. E-commerce businesses also need abandoned cart and post-purchase sequences. I recommend starting with 3-5 core sequences and expanding based on performance data.' },
      { question: 'What email open rates can I expect?', answer: 'Healthy open rates vary by industry, but with proper segmentation and list hygiene, most clients achieve 25-45% open rates and 3-8% click-through rates. The key is sending relevant content to segmented audiences rather than blasting your entire list.' },
      { question: 'How do you improve email deliverability?', answer: 'I configure authentication records (SPF, DKIM, DMARC), warm up new sending domains gradually, implement list hygiene practices to remove inactive contacts, monitor sender reputation through tools like Google Postmaster, and optimize sending patterns to maintain high inbox placement rates.' },
      { question: 'Do you write the email content?', answer: 'I write all email copy for automation sequences including subject lines, body content, and CTAs. For ongoing newsletter or campaign content, I can either write it as an add-on service or provide templates and guidelines for your team to follow.' },
    ],
    relatedSlugs: ['automation-n8n', 'martech-consulting', 'social-media-marketing'],
  },
};
